spring:
  application:
    name: haetsal-service
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/haetsal?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      highlight-sql: true
      ddl-auto: create

      dialect: org.hibernate.dialect.MySQLDialect # ??? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # ?? ?? ??
    generate-ddl: true

  sql:
    init:
      mode: always

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    path: /api/docs/v1
springdoc:
  api-docs:
    enabled: true
    path: /api/docs/v1
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    default-models-expand-depth: 2
    default-model-expand-depth: 2
    display-operation-id: false
    show-extensions: false
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
#  paths-to-match:
#    - /api/v2/**

server:
  port: 80


s3:
  access-key: ${access-key}
  secret-key: ${secret-key}

# 유레카
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://host.docker.internal:8761/eureka
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com.eum.haetsal: debug