#로컬 개발 시 사용하는 YML
#DB 정보를 .env에 작성해서 실행한다. feign-client와 kafka는 dev 서버 정보로 실행한다.

feign-client:
  url:
    bank-service: ${BANK_SERVICE_DEV_URL_PORT}
    chat-service: ${CHAT_SERVICE_DEV_URL_PORT}
    auth-service: ${AUTH_SERVICE_DEV_URL_PORT}

kafka:
  bootstrap-servers: ${KAFKA_DEV_BOOTSTRAP_SERVERS}

spring:
  datasource:
    url: jdbc:mysql://${HAETSAL_LOCAL_DB_IP}:${HAETSAL_LOCAL_DB_PORT}/${HAETSAL_LOCAL_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${HAETSAL_LOCAL_DB_USERNAME}
    password: ${HAETSAL_LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO
    com.eum.haetsal: DEBUG
    org.springframework:
      web: DEBUG
      security: INFO